#Nginx server
# FROM nginx:stable-alpine
# COPY build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# CMD ["nginx", "-g", "daemon off;"]

# npm server
FROM node:alpine
WORKDIR /app
RUN npm i -g serve
COPY build ./
CMD ["serve", "-s", "build"]