version: '3'
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    command: bash -c "nginx -g 'daemon off;'"
    ports:
      - '80:80'
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
      - web
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: '${PG_PASS}'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: iliyany/ninja-store:cores
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SECRET_KEY_BASE="${KEY_BASE}"
      - RAILS_ENV=production
      - 'DATABASE_URL=postgres://postgres:${PG_PASS}@db:5432'
      - JWT_SECRET
      - ADMIN_EMAIL
      - MAILER_SENDER
      - MAILER_PASSWORD
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - END_POINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - db
  web:
    image: rails-web
    depends_on:
      - app
    ports:
      - 5000:5000
  react-app:
    image: test-react-app
    ports:
      - '3002:3002'
    volumes:
      - ../test-apps/react-typescript-router/nginx.conf:/etc/nginx/nginx.conf
      - ../test-apps/react-typescript-router/build:/usr/share/nginx/html
volumes:
  postgres-data:
