version: '3'
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    command: sh -c "nginx -g 'daemon off;'"
    ports:
      - '80:80'
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 'app-rails'
      - 'test-react-app'
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: '${PG_PASS}'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database
  rails-app:
    image: iliyany/ninja-store:no-cores
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SECRET_KEY_BASE="${KEY_BASE}"
      - RAILS_ENV=production
      - 'DATABASE_URL=postgres://postgres:${PG_PASS}@db:5432'
      - RAILS_SERVE_STATIC_FILES=true
      - JWT_SECRET
      - ADMIN_EMAIL
      - MAILER_SENDER
      - MAILER_PASSWORD
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - END_POINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - '3000:3000'
    depends_on:
      - db
  react-app:
    image: test-react-app
    ports:
      - '4567:4567'
    depends_on:
      - 'app-rails'
volumes:
  postgres-data:
